# 공통 환경
spring:
  profiles:
    active: develop

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    database: mysql
    show-sql: true

